<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Python Environments on Narendra Kumar</title>
    <link>/tags/python-environments/</link>
    <description>Recent content in Python Environments on Narendra Kumar</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <copyright>&amp;copy; Narendra Kumar {year} </copyright>
    <lastBuildDate>Mon, 24 Jun 2019 20:05:49 +0530</lastBuildDate>
    
	<atom:link href="/tags/python-environments/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Creating New Environment With Anaconda</title>
      <link>/post/creating-new-environment-with-anaconda/</link>
      <pubDate>Mon, 24 Jun 2019 20:05:49 +0530</pubDate>
      
      <guid>/post/creating-new-environment-with-anaconda/</guid>
      <description>Today I was working with networkx API and wanted to draw CircosPlot of a sample of GitHub user collaboration data . I had networkx, nxviz, matplotlib installed in my current shell environment so plotting should have been eventless.
import networkx as nx import matplotlib.pyplot as plt import nxviz as nv G = nx.read_gpickle(&#39;github.p&#39;)  Before moving further I decided to check if everything was ok&amp;hellip;
G.nodes()  --------------------------------------------------------------------------- AttributeError Traceback (most recent call last) &amp;lt;ipython-input-3-083f395b092f&amp;gt; in &amp;lt;module&amp;gt; ----&amp;gt; 1 G.</description>
    </item>
    
  </channel>
</rss>